import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://shop-do-bao-ho.onrender.com/');
  await page.getByText('Đăng nhập/Đăng ký').click();
  await page.getByRole('textbox', { name: 'abc@gmail.com' }).click();
  await page.getByRole('textbox', { name: 'abc@gmail.com' }).fill('abc@gmail.com');
  await page.getByRole('textbox', { name: 'password' }).click();
  await page.getByRole('textbox', { name: 'password' }).fill('123456');
  await page.getByRole('button', { name: 'Đăng nhập' }).click();
  await page.getByText('Quần Riding Tribe HP-08150,').click();
  await page.getByRole('button', { name: 'plus' }).click();
  await page.getByRole('button', { name: 'plus' }).click();
  await page.getByRole('button', { name: 'Chọn mua' }).click();
  await page.getByText('1Giỏ hàng').click();
  await page.getByLabel('', { exact: true }).nth(1).check();
  await page.getByText('Địa chỉ:', { exact: true }).click();
  await page.getByText('Da Nang').click();
  await page.getByText('Kiểm tra thông tin trước khi').click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.locator('div').filter({ hasText: /^NameCập nhật$/ }).getByRole('button').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.locator('div').filter({ hasText: /^EmailCập nhật$/ }).getByRole('button').click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.locator('div').filter({ hasText: /^PhoneCập nhật$/ }).getByRole('button').click();
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.locator('div').filter({ hasText: /^AddressCập nhật$/ }).getByRole('button').click();
  await page.getByText('Name').click();
  await page.getByText('Email', { exact: true }).click();
  await page.getByText('Phone').click();
  await page.getByText('Address').click();
  await page.getByText('1Giỏ hàng').click();
  await page.getByRole('button', { name: 'Mua hàng' }).click();
  await page.getByLabel('', { exact: true }).nth(1).check();
  await page.getByRole('button', { name: 'Mua hàng' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('radio', { name: 'GO_JEK Giao hàng tiết kiệm' }).check();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
});